### ISSUE TITLE
DNX/CoreFX support

### ISSUE THREAD

**Issue by salerth** [maxhauser/semver#11]
Any thoughts on supporting the new DNX framework for this?  Either directly or via the portable framework?

Currently I had to remove any of the String.Intern & Serialization stuff to make it work. The serialization stuff is a breaking change but I didnt want yet another semver library on nuget!

**Comment by maxhauser** [comment]
I agree, that DNX is definitely something that *should* be supported by such a library. I will look into this, but I cannot make any guarantees when this will happen.

So any pull requests are very welcome.

**Comment by kenbrubaker** [comment]
Will you still take PR's for this and publish to NuGet?

**Comment by maxhauser** [comment]
Oh - you are absolutely right, its seams that I did not check-in the nuspec file with the updated version. With the exception of the nuspec file the repository is up to date. I will happily take PRs. So when you have one in the making, I will wait for it and then push the version to 1.1.3 and publish it to nuget.

**Comment by niemyjski** [comment]
@maxhauser any chance you could add me as a collaborator.. I can help manage releases + convert to core..

**Comment by maxhauser** [comment]
@niemyjski I appreciate any help - I added you as collaborator
sorry for the delay - I was on vacation w/o network access

**Comment by niemyjski** [comment]
https://github.com/maxhauser/semver/pull/20
