### ISSUE TITLE
About ordering (seems that's becoming my speciality :))

### ISSUE THREAD

**Issue by olivier-spinelli** [maxhauser/semver#15]
Since it is not strictly a  bug, I'm opening an issue here.
The semver specification explicitly states that:

"Build metadata SHOULD be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85."

However, the Build metadata is actually considered in CompareTo method:

```
    public int CompareTo(SemVersion other)
    {
        if (ReferenceEquals(other, null))
            return 1;

        var r = this.CompareByPrecedence(other);
        if (r != 0)
            return r;

        r = CompareComponent(this.Build, other.Build);
        return r;
    }
```

Up to me, it should only be:

```
    public int CompareTo(SemVersion other)
    {
        if (ReferenceEquals(other, null))
            return 1;

        return CompareByPrecedence(other);
    }
```

**Comment by maxhauser** [comment]
The CompareTo method should provide stable results. Otherwise structures that depend on ordering will not work as expected (like Dictionaries).
To compare by precedence please use the method CompareByPrecedence or PrecedenceMatches.

See also https://github.com/maxhauser/semver/issues/9.

**Comment by olivier-spinelli** [comment]
Ok, I understand your choice. Mine would have been to support/enforce equality and comparison semantics of SemVer on the SemVersion object (forgetting the Build metadata), leaving the ToString() representation as a key to the developer that needs to manipulate the whole version.
(And thanks for having so quickly merged my PRs)

**Comment by maxhauser** [comment]
I am not totally happy with this design myself, but in my opinion CompareTo should only return 0 when Equals returns true - and that should be only on semantically equal objects. And thats not the case when the build metadata is different.

Maybe a own IComparer implementation for comparing by precedence would make the choice more explicit.

**Comment by olivier-spinelli** [comment]
That's exactly my point: semantically, the Build does not participate at all (It is a "decoration"): I would ignore it in CompareTo as well as in Equal (and document this of course).

**Comment by WalkerCodeRanger** [comment]
I agree this needs to be addressed. Issue #9 was about the same confusion. The final fix may have to go into v3, but there may be groundwork to be laid before then.

**Comment by olivier-spinelli** [comment]
Hi guys, FYI I made my own version of this to support https://csemver.org/ (This was an interesting challenge since basically it's the Square-Rectangle or Ellipse-Circle problem that I wanted to investigate and eventually support).

My final SVersion implementation is here. 
https://github.com/CK-Build/CSemVer-Net/blob/master/CSemVer/SVersion.cs

It's a bit different than the one of SemVer but it may interest some of you.

**Comment by WalkerCodeRanger** [comment]
In v2.2.0, the `CompareTo` method has been marked `[Obsolete]`. It has been replaced by a `CompareSortOrderTo` and `ComparePrecedenceTo` method so that it will always be clear how the versions are being compared.
