### ISSUE TITLE
Parse "strict mode" allows leading zeroes, invalid pre-release identifiers

### ISSUE THREAD

**Issue by zarenner** [maxhauser/semver#16]
Per http://semver.org/#spec-item-2
"A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and MUST NOT contain leading zeroes."

The strict parameter in Parse/TryParse should either perform this validation (which would be a breaking semantic change), or another parameter should be added to allow enforcing this.  Thoughts?

I'm happy to contribute a fix.

**Comment by WalkerCodeRanger** [comment]
I'm hoping to improve this with issue #38 "Improve Parsing Options", but the actual breaking change will have to be in v3.0.

**Comment by WalkerCodeRanger** [comment]
Since it may not be obvious, the title refers to version strings like "1.0.0-alpha.01" which is invalid according to the BNF in the spec because the prerelease segment "01" is not a valid numeric segment.

**Comment by WalkerCodeRanger** [comment]
The new parsing methods in v2.1.0 fix this. The old parsing methods are obsolete and will be removed in v3.0.0.
