### ISSUE TITLE
Republished as .net core compatible nuget package

### ISSUE THREAD

**Issue by apawsey** [maxhauser/semver#19]
This has been republished at https://www.nuget.org/packages/semver.core as a .net core compatible version.  The project site is https://github.com/apawsey/semver for issues.  I will have a look at the existing issues listed on this repository and see if they can be resolved in the new package.

**Comment by stefc** [comment]
Thank for this fork of semver. It helps me a lot of using semver for a .NET core project. BTW did you know how to use the `dotnet build --version-suffix <suffix>` option? I can't get it run correctly!

**Comment by herecydev** [comment]
This can probably be closed now that the `.net core` compatibility has been added.
