### ISSUE TITLE
Strong name package

### ISSUE THREAD

**Issue by vadimi** [maxhauser/semver#22]
I'd like to use that library, but all projects in my solution are strong named. Any chance we can get a strong name version of the package? Maybe something similar to Dapper: 

[https://www.nuget.org/packages/Dapper.StrongName/](https://www.nuget.org/packages/Dapper.StrongName/)

**Comment by Sam13** [comment]
+1

**Comment by WalkerCodeRanger** [comment]
Closing this as a duplicate of issue #23
