### ISSUE TITLE
Migrate *.proj files to latest .net version

### ISSUE THREAD

**Issue by ahryshchanka** [maxhauser/semver#28]

**Comment by grishchenkoa** [comment]
Is it project actual? 245 074 downloads for last version 2.0.4

Does it make sense to update project to last version?

**Comment by iron9light** [comment]
And target .NET Standard 2.0 as well.

**Comment by WalkerCodeRanger** [comment]
I'll definitely be upgrading the project files. Going to .NET Standard 2.0 may have to wait for v3, but I'll look into it.

**Comment by WalkerCodeRanger** [comment]
Moving to .NET Standard 2.0 will have to wait as it is a breaking change. I've created issue #30 for it.

**Comment by WalkerCodeRanger** [comment]
Solution and projects are setup with VS 2019. Appveyor builds correctly and assigns version numbers.

Releases can be created by tagging a commit as demonstrated in the build https://ci.appveyor.com/project/maxhauser/semver/builds/28310520
