### ISSUE TITLE
SemVersion.Satisfies method?

### ISSUE THREAD

**Issue by chadly** [maxhauser/semver#7]
It would be nice to have a method on SemVersion that would determine whether or not the version satisfies a particular version string.

E.g.

``` cs
SemVersion ver = new SemVersion(1, 2, 3);
Assert.True(ver.Satisfies("1.2.x"));
Assert.True(ver.Satisfies(">=1.0"));
Assert.False(ver.Satisfies("1.3"));
```

etc.

**Comment by WalkerCodeRanger** [comment]
I definitely think it would be good to include functionality for some kind of range matching. I've created issue #29 for that.

Given that different platforms and libraries use different syntax for specifying version requirements, how would you see this working? How could we decide on a preferred syntax?
