### ISSUE TITLE
System.OverflowException: 'Prerelease identifier 'xxx' was too large for Int32 in version 'xxx'.'

### ISSUE THREAD

**Issue by specialforest** [maxhauser/semver#73]
An example version: "1.0.0-202208281200".
I don't see the spec limits pre-release numeric parts to 2^31 range.

**Comment by WalkerCodeRanger** [comment]
The semver spec does not give an upper limit to numeric prerelease identifiers nor of the major, minor, or patch. However, for ease of developer use `int` was used for these. It was thought unlikely people would run into those limits. For v3.0 of the library, we can consider using `long` or `BigInteger`.

In the mean time, I would suggest turning into an alphanumeric prerelease identifier following the ISO 8601 standard (e.g. `1.0.0-2022-08-28.1200`) or dot separating each of the parts (e.g. `1.0.0-2022.08.28.1200`)

**Comment by damepatr** [comment]
> The semver spec does not give an upper limit to numeric prerelease identifiers nor for the **major, minor, or patch**.

Yeah, I am encountering the same issue with the patch number. I would definitely be interested in a fix.

**Comment by WalkerCodeRanger** [comment]
@damepatr To help me understand the use case and how to best address it, how are you getting patch numbers so high? Also, what is the highest patch number you would anticipate needing?

**Comment by damepatr** [comment]
@WalkerCodeRanger

> To help me understand the use case and how to best address it, how are you getting patch numbers so high?

I used the date and time to create a patch number similar to the following: `1.1.20221227164407`.

I know that this probably isn't a best practice. I was just testing some of my own code and I noticed that `SemVersion.TryParse` was returning `false` when this _technically_ is valid SemVer.

**Comment by damepatr** [comment]
> Also, what is the highest patch number you would anticipate needing?

At the moment, I'm not certain. I may not need a larger patch number.

**Comment by WalkerCodeRanger** [comment]
A preview of this feature has been released in the `3.0.0-beta.0` version available on NuGet.

**Comment by WalkerCodeRanger** [comment]
This has been fixed on master and will be included in v3.0.0

**Comment by Falco20019** [comment]
Is there a timeline on when 3.x is expected to be released? [3.0.0-beta.1](https://www.nuget.org/packages/Semver/3.0.0-beta.1) has been out for close to a year now.

**Comment by WalkerCodeRanger** [comment]
I've just answered this in #83 . I'll try to get it out on or before 2024-09-30.
