### ISSUE TITLE
INotifyPropertyChanged? 

### ISSUE THREAD

**Issue by dazinator** [maxhauser/semver#8]
I'd like to create a Winforms user control for input of a semver version number. Would it be possible for you to implement INotifiyProperty changed as then I could databind directly to this class..

**Comment by wallymathieu** [comment]
You could create a semver class that wraps this class in order to be able to have INotifyPropertyChanged on each property exposed?

**Comment by WalkerCodeRanger** [comment]
The `SemVersion` class is an immutable value type. No methods or properties modify the object. So there would be nothing to raise property change on. If you had a class that implemented `INotifyPropertyChanged` that had a `SemVersion` property on it, you'd have to assign a new version object into it to change the version. That would cause the property to raise a changed event.
