### ISSUE TITLE
semver is not according to semver 2.0 spec

### ISSUE THREAD

**Issue by eggapauli** [maxhauser/semver#9]
The tests below don't meet the semver 2.0 spec

http://semver.org/

> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. __Build metadata SHOULD be ignored when determining version precedence.__ Thus two versions that differ only in the build metadata, have the same precedence. 

```
        [TestMethod]
        public void CompareTest7()
        {
            var v1 = SemVersion.Parse("0.0.1");
            var v2 = SemVersion.Parse("0.0.1+build.12");

            var r = v1.CompareTo(v2);
            Assert.AreEqual(-1, r);
        }

        [TestMethod]
        public void CompareTest8()
        {
            var v1 = SemVersion.Parse("0.0.1+build.13");
            var v2 = SemVersion.Parse("0.0.1+build.12.2");

            var r = v1.CompareTo(v2);
            Assert.AreEqual(1, r);
        }
```

**Comment by maxhauser** [comment]
The CompareTo method is to determine a sort order and is not to be confused with the precedence of versions. To get the precedence use the method CompareByPrecedence or PrecedenceMatches. Those methods ignore the build metadata.

**Comment by eggapauli** [comment]
Ohh, I see, got it. Thanks for clarifying that.
